insert into MAKES (c_id, trade_name) values (501, 'Hydrocodone Bitartrate ');
insert into MAKES (c_id, trade_name) values (502, 'carvedilol');
insert into MAKES (c_id, trade_name) values (503, 'hemorrhoidal');
insert into MAKES (c_id, trade_name) values (504, 'Hepar Sulph Calc Kit Refill');
insert into MAKES (c_id, trade_name) values (505, 'EAR INFLAM HP');
insert into MAKES (c_id, trade_name) values (506, 'CIPROFLOXACIN');
insert into MAKES (c_id, trade_name) values (507, 'Plegridy');
insert into MAKES (c_id, trade_name) values (508, 'Plegridy');
insert into MAKES (c_id, trade_name) values (509, 'Hepar Sulph Calc Kit Refill');
insert into MAKES (c_id, trade_name) values (510, 'Pretty in Paris Kit');
insert into MAKES (c_id, trade_name) values (501, 'Doxepin Hydrochloride');
insert into MAKES (c_id, trade_name) values (503, 'Hepar Sulph Calc Kit Refill');
insert into MAKES (c_id, trade_name) values (504, 'EAR INFLAM HP');
insert into MAKES (c_id, trade_name) values (505, 'carvedilol');
insert into MAKES (c_id, trade_name) values (506, 'Quazepam');
insert into MAKES (c_id, trade_name) values (507, 'hemorrhoidal');
insert into MAKES (c_id, trade_name) values (508, 'Quazepam');
insert into MAKES (c_id, trade_name) values (509, 'Hydrocodone Bitartrate ');
insert into MAKES (c_id, trade_name) values (510, 'Pyrite 8');
insert into MAKES (c_id, trade_name) values (502, 'Doxepin Hydrochloride');
insert into MAKES (c_id, trade_name) values (503, 'carvedilol');
insert into MAKES (c_id, trade_name) values (504, 'Neova Day Therapy');
insert into MAKES (c_id, trade_name) values (505, 'Neova Day Therapy');
insert into MAKES (c_id, trade_name) values (506, 'Hepar Sulph Calc Kit Refill');
insert into MAKES (c_id, trade_name) values (507, 'Hydrocodone Bitartrate ');
insert into MAKES (c_id, trade_name) values (508, 'XtraCare Sanitizer');
insert into MAKES (c_id, trade_name) values (509, 'carvedilol');
insert into MAKES (c_id, trade_name) values (510, 'Quazepam');
